name: ci

on:
  push:
    paths:
    - '**.go'
    - '**.mod'
    - 'go.sum'
  workflow_dispatch:


jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.63.4

  semgrep:
    name: sast
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep scan
      run: semgrep scan --config=p/gosec --disable-version-check --oss-only --metrics=off --verbose .

  go-test:
    runs-on: ubuntu-latest
    needs:
    - golangci
    - semgrep
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.6'

    - name: Test with the Go CLI
      run: go test ./...

  go-build:
    runs-on: ubuntu-latest
    needs: go-test
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.6'

    - name: Build with the Go CLI
      run: go build -v -o message-app cmd/api/main.go
