name: Dispatch cnspec scan

on:
  workflow_dispatch:


jobs:
  trigger-target-repo:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - name: Send repo dispatch event
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${TARGET_REPO_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${TARGET_REPO}/dispatches \
          -d '{"event_type":"trigger-scan","client_payload":{"integration":true}}'

      env:
        TARGET_REPO: ${{ secrets.TARGET_REPO }}
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
