name: Dispatch cnspec scan

on:
  workflow_dispatch:


jobs:
  trigger-target-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch full history including tags

    - name: Get the Latest Git Tag
      run: |
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        if [ -z "$TAG" ]; then
          echo "No tag found! Stopping workflow."
          exit 1
        fi
        echo "GIT_TAG=$TAG" >> $GITHUB_ENV

    - name: Send repo dispatch event
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${TARGET_REPO_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${TARGET_REPO}/dispatches \
          -d '{"event_type":"trigger-scan","client_payload":{"integration":true,"version":"'"${GIT_TAG}"'"}}'

      env:
        TARGET_REPO: ${{ secrets.TARGET_REPO }}
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
