name: Dispatch cnspec scan

on:
  workflow_dispatch:


jobs:
  trigger-target-repo:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - name: Send repo dispatch event
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${TARGET_REPO}/dispatches \
          -f "event_type=trigger-scan" \
          -F "client_payload[integration]=true"

      env:
        TARGET_REPO: ${{ secrets.TARGET_REPO }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
