name: Go build

on:
  workflow_dispatch:


jobs:
  go-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.6'

    - name: Build with the Go CLI
      run: go build -v -o message-app cmd/api/main.go
