name: Static Application Security Testing
## Only trigger tests if source has changed
on:
  push:
    paths:
    - '**.go'
    - '**.mod'
    - 'go.sum'
  workflow_dispatch:


jobs:
  semgrep:
    name: sast
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep scan
      run: semgrep scan --config=p/gosec --disable-version-check --oss-only --metrics=off --verbose .
