name: Go testing

## Only trigger tests if source has changed
on:
  push:
    paths:
    - '**.go'
    - '**.mod'
    - 'go.sum'
  workflow_dispatch:


jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.6'

    - name: Test with the Go CLI
      run: go test ./...
